### ISSUE TITLE
[jspd-admin] number of urusetia melebihi 2+

### ISSUE THREAD

**Issue by fiey057** [azrilnazli/ukk-backend#12]
PID: 1504
(https://user-images.githubusercontent.com/67974064/173235484-3030f661-82d6-4ac2-abda-b3b656235362.png)

**Comment by azrilnazli** [comment]
done

**Comment by fiey057** [comment]
Masih ada

(https://user-images.githubusercontent.com/67974064/173270635-ed3f527a-b35b-4a30-bdc1-8315d295a5c5.png)
