### ISSUE TITLE
[JSPD-admin] status changes

### ISSUE THREAD

**Issue by fiey057** [azrilnazli/ukk-backend#21]
Status di Proposal menu: (https://user-images.githubusercontent.com/67974064/173730238-296ac18d-0e31-4d0f-aab2-1b0adec3d09f.png)

Status:
lulus (green) / gagal (red) - admin dah tanda
belum ditanda (yellow) - admin belum tanda
belum selesai (grey) - proposal belum assign/belum complete pengesahan

Lists di menu Lulus/Gagal betul, saya dah cek

**Comment by azrilnazli** [comment]
try check balik

**Comment by fiey057** [comment]
belum ditanda (yellow) tu untuk yg dah complete (panel 3/3, urusetia 2/2) sahaja.

**Comment by fiey057** [comment]
final status:
selesai - admin dah tanda
lulus/gagal - dah complete, tgu admin tanda
belum ditanda oleh penanda - 3 penanda tk tanda lgi
belum disahkan oleh urusetia - 2 urusetia belum buat pengesahan
proposal belum assign - urusetia belum assign proposal
